services:

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres_db:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      - back-end/.env
    
  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - react_build:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react_build:/var/www/html
    depends_on:
      - postgres_db
      - node_app
      - react_app

volumes:
  postgres_db:
  react_build: