on:
  push:
    branches:
      - main

name: Build and Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "app_sorteio"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres_db:5432/app_sorteio"
          file_name: back-end/.env
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_BASE_URL: "http://ec2-34-207-85-145.compute-1.amazonaws.com/API"
          file_name: front-end/.env
          fail_on_empty: true

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down -v && docker-compose up -d
